"""Committed S07 haul-route PLANS — GENERATED, do not edit by hand.

Each entry is one haul-route plan (loaded climb + empty return node paths, the OR-Tools CP-SAT cost
certificate, the analytic g* reference, and the route-trace render geometry) for one fixed geometry. They are
*rendered data only* — node ids + numbers, never a raw graph — so they ship safely in the public repo and the
live SimPy replay (``s07_haul.py``) loads them WITHOUT importing OR-Tools/NetworkX (no WASM build).

Regenerate with:  python -m simlab.scenarios._haul_plan   (runs the native NetworkX+OR-Tools builder offline).
"""
from __future__ import annotations

PLANS = {'g12_grade0.0_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 0.0,
                                   'grid': 12,
                                   'key': 'g12_grade0.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 11.0,
                                   'up_cost_certified': 11.0,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade0.0_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 0.0,
                                   'grid': 12,
                                   'key': 'g12_grade0.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 13.0,
                                   'up_cost_certified': 13.0,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 100, 112, 124, 136]},
 'g12_grade0.5_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 0.5,
                                   'grid': 12,
                                   'key': 'g12_grade0.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 11.6315,
                                   'up_cost_certified': 11.63,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade0.5_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 0.5,
                                   'grid': 12,
                                   'key': 'g12_grade0.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 13.3748,
                                   'up_cost_certified': 13.374,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 112, 124, 136]},
 'g12_grade1.0_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 1.0,
                                   'grid': 12,
                                   'key': 'g12_grade1.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 12.2629,
                                   'up_cost_certified': 12.265,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade1.0_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 1.0,
                                   'grid': 12,
                                   'key': 'g12_grade1.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 13.7497,
                                   'up_cost_certified': 13.751,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 123, 135, 136]},
 'g12_grade1.5_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 1.5,
                                   'grid': 12,
                                   'key': 'g12_grade1.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 12.8944,
                                   'up_cost_certified': 12.896,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade1.5_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 1.5,
                                   'grid': 12,
                                   'key': 'g12_grade1.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 14.1245,
                                   'up_cost_certified': 14.126,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 112, 124, 136]},
 'g12_grade2.0_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 2.0,
                                   'grid': 12,
                                   'key': 'g12_grade2.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 13.5258,
                                   'up_cost_certified': 13.526,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade2.0_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 2.0,
                                   'grid': 12,
                                   'key': 'g12_grade2.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 14.4994,
                                   'up_cost_certified': 14.499,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 112, 124, 136]},
 'g12_grade2.5_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 2.5,
                                   'grid': 12,
                                   'key': 'g12_grade2.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 14.1573,
                                   'up_cost_certified': 14.156,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade2.5_pass2_lift4_bar1': {'analytic': {'cross_col': 3,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 3',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 2.5,
                                   'grid': 12,
                                   'key': 'g12_grade2.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 14.8742,
                                   'up_cost_certified': 14.873,
                                   'up_path': [4, 3, 15, 27, 39, 51, 63, 75, 87, 99, 111, 112, 124, 136]},
 'g12_grade3.0_pass2_lift4_bar0': {'analytic': {'cross_col': 4,
                                                'lift_col': 4,
                                                'route_via': 'direct over crest',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 3.0,
                                   'grid': 12,
                                   'key': 'g12_grade3.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 14.7887,
                                   'up_cost_certified': 14.79,
                                   'up_path': [4, 16, 28, 40, 52, 64, 76, 88, 100, 112, 124, 136]},
 'g12_grade3.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 3.0,
                                   'grid': 12,
                                   'key': 'g12_grade3.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.2375,
                                   'up_cost_certified': 15.239,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade3.5_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 3.5,
                                   'grid': 12,
                                   'key': 'g12_grade3.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.2771,
                                   'up_cost_certified': 15.278,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade3.5_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 3.5,
                                   'grid': 12,
                                   'key': 'g12_grade3.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.2771,
                                   'up_cost_certified': 15.278,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade4.0_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 4.0,
                                   'grid': 12,
                                   'key': 'g12_grade4.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3166,
                                   'up_cost_certified': 15.315,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade4.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 4.0,
                                   'grid': 12,
                                   'key': 'g12_grade4.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3166,
                                   'up_cost_certified': 15.315,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade4.5_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 4.5,
                                   'grid': 12,
                                   'key': 'g12_grade4.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3562,
                                   'up_cost_certified': 15.354,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               122,
                                               134,
                                               135,
                                               136]},
 'g12_grade4.5_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 4.5,
                                   'grid': 12,
                                   'key': 'g12_grade4.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3562,
                                   'up_cost_certified': 15.354,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               122,
                                               134,
                                               135,
                                               136]},
 'g12_grade5.0_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 5.0,
                                   'grid': 12,
                                   'key': 'g12_grade5.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3958,
                                   'up_cost_certified': 15.397,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade5.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 5.0,
                                   'grid': 12,
                                   'key': 'g12_grade5.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.3958,
                                   'up_cost_certified': 15.397,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade5.5_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 5.5,
                                   'grid': 12,
                                   'key': 'g12_grade5.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.4354,
                                   'up_cost_certified': 15.436,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade5.5_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 5.5,
                                   'grid': 12,
                                   'key': 'g12_grade5.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.4354,
                                   'up_cost_certified': 15.436,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade6.0_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 6.0,
                                   'grid': 12,
                                   'key': 'g12_grade6.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.475,
                                   'up_cost_certified': 15.473,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               123,
                                               135,
                                               136]},
 'g12_grade6.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 6.0,
                                   'grid': 12,
                                   'key': 'g12_grade6.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.475,
                                   'up_cost_certified': 15.473,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               123,
                                               135,
                                               136]},
 'g12_grade6.0_pass9_lift7_bar0': {'analytic': {'cross_col': 9,
                                                'lift_col': 7,
                                                'route_via': 'pass at col 9',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [139, 127, 115, 103, 91, 79, 67, 55, 43, 31, 19, 7],
                                   'dump_node': 139,
                                   'grade': 6.0,
                                   'grid': 12,
                                   'key': 'g12_grade6.0_pass9_lift7_bar0',
                                   'lift_col': 7,
                                   'load_node': 7,
                                   'pass_col': 9,
                                   'up_cost': 15.475,
                                   'up_cost_certified': 15.473,
                                   'up_path': [7,
                                               8,
                                               9,
                                               21,
                                               33,
                                               45,
                                               57,
                                               69,
                                               81,
                                               93,
                                               105,
                                               117,
                                               116,
                                               128,
                                               140,
                                               139]},
 'g12_grade6.5_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 6.5,
                                   'grid': 12,
                                   'key': 'g12_grade6.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5145,
                                   'up_cost_certified': 15.516,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade6.5_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 6.5,
                                   'grid': 12,
                                   'key': 'g12_grade6.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5145,
                                   'up_cost_certified': 15.516,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade7.0_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 7.0,
                                   'grid': 12,
                                   'key': 'g12_grade7.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5541,
                                   'up_cost_certified': 15.555,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade7.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 7.0,
                                   'grid': 12,
                                   'key': 'g12_grade7.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5541,
                                   'up_cost_certified': 15.555,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               110,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade7.5_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 7.5,
                                   'grid': 12,
                                   'key': 'g12_grade7.5_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5937,
                                   'up_cost_certified': 15.592,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade7.5_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 7.5,
                                   'grid': 12,
                                   'key': 'g12_grade7.5_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.5937,
                                   'up_cost_certified': 15.592,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade8.0_pass2_lift4_bar0': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': 3.38},
                                   'barrier': 0,
                                   'down_path': [136, 124, 112, 100, 88, 76, 64, 52, 40, 28, 16, 4],
                                   'dump_node': 136,
                                   'grade': 8.0,
                                   'grid': 12,
                                   'key': 'g12_grade8.0_pass2_lift4_bar0',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.6333,
                                   'up_cost_certified': 15.632,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]},
 'g12_grade8.0_pass2_lift4_bar1': {'analytic': {'cross_col': 2,
                                                'lift_col': 4,
                                                'route_via': 'pass at col 2',
                                                'switch_grade_est': None},
                                   'barrier': 1,
                                   'down_path': [136, 124, 112, 100, 99, 87, 75, 63, 51, 39, 27, 15, 3, 4],
                                   'dump_node': 136,
                                   'grade': 8.0,
                                   'grid': 12,
                                   'key': 'g12_grade8.0_pass2_lift4_bar1',
                                   'lift_col': 4,
                                   'load_node': 4,
                                   'pass_col': 2,
                                   'up_cost': 15.6333,
                                   'up_cost_certified': 15.632,
                                   'up_path': [4,
                                               3,
                                               2,
                                               14,
                                               26,
                                               38,
                                               50,
                                               62,
                                               74,
                                               86,
                                               98,
                                               99,
                                               111,
                                               112,
                                               124,
                                               136]}}
