"""In-browser (Pyodide) entrypoint for the live param-tuning lane.

Imported AFTER numpy is loaded into the WASM runtime. `run_trace_json` shares the EXACT run + serialise
path the offline pipeline uses (``Scenario.run`` -> ``Trace.to_json``), so a live run of (scenario, params,
seed) is byte-comparable to the committed trace generated by ``python -m simlab.pipeline``. Native-engine
scenarios (OR-Tools) are refused here as a hard guard so the lazy ortools import is never reached in WASM.
"""
from __future__ import annotations

import json

from .registry import SCENARIOS, get_scenario


def live_lanes() -> list[str]:
    """Scenario ids the browser is allowed to run live (pure-Python engines only)."""
    return [sid for sid, sc in SCENARIOS.items() if sc.pure_python]


def run_trace_json(scenario_id: str, params: dict, seed: int) -> str:
    """Run one scenario and return its compact trace JSON (identical bytes to the committed trace)."""
    sc = get_scenario(scenario_id)
    if not sc.pure_python:  # defence in depth: the UI also gates this
        raise RuntimeError(f"{scenario_id} is precompute-only (native engine, cannot run in WASM)")
    coerced = sc.coerce(params)
    tr = sc.run(coerced, int(seed))
    return tr.to_json()


# A tiny self-check usable from CPython too (the web worker calls run_trace_json directly).
if __name__ == "__main__":  # pragma: no cover
    print(json.dumps({"live_lanes": live_lanes()}))
