"""In-browser (Pyodide) entrypoint for the live param-tuning lane.

Imported AFTER numpy is loaded into the WASM runtime. `run_trace_json` shares the EXACT run + serialise
path the offline pipeline uses (``Scenario.run`` -> ``Trace.to_json``), so a live run of (scenario, params,
seed) is byte-comparable to the committed trace generated by ``python -m simlab.pipeline``. Native-engine
scenarios (OR-Tools) are refused here as a hard guard so the lazy ortools import is never reached in WASM.
"""
from __future__ import annotations

import json

from .core.scenario import LIVE_WHEELS
from .registry import SCENARIOS, get_scenario


def _is_live(sc) -> bool:
    """A scenario runs live only if its engine is pure-Python AND its wheel closure is one the browser
    worker actually loads (LIVE_WHEELS = numpy, simpy, ciw, mesa, pandas, scipy, networkx, sqlite3,
    joblib). Mesa (ABM), joblib/scipy (Monte-Carlo) and networkx (graphs) are all IN LIVE_WHEELS and run
    live — only NATIVE engines (OR-Tools, pure_python=False) are precompute-only and replayed."""
    return sc.pure_python and set(sc.wheels) <= LIVE_WHEELS


def live_lanes() -> list[str]:
    """Scenario ids the browser is allowed to run live (matches the manifest lane verdict)."""
    return [sid for sid, sc in SCENARIOS.items() if _is_live(sc)]


def run_trace_json(scenario_id: str, params: dict, seed: int) -> str:
    """Run one scenario and return its compact trace JSON (identical bytes to the committed trace)."""
    sc = get_scenario(scenario_id)
    if not _is_live(sc):  # defence in depth: the UI also gates this
        raise RuntimeError(f"{scenario_id} is precompute-only (engine/wheels not in the live worker)")
    coerced = sc.coerce(params)
    tr = sc.run(coerced, int(seed))
    return tr.to_json()


# A tiny self-check usable from CPython too (the web worker calls run_trace_json directly).
if __name__ == "__main__":  # pragma: no cover
    print(json.dumps({"live_lanes": live_lanes()}))
